hello:
  description: Hello
  type: string
  required: false
  default: world
sleep:
  description: Sleep (seconds)
  type: integer
  required: false
  default: 60
things:
  description: Things
  type: array
  required: false
  default: []
