hello:
  description: Hello
  type: string
  required: false
  default: world
sleep:
  description: Sleep (seconds)
  type: integer
  required: false
  default: 300
things:
  description: Things
  type: list
  required: false
  default: []
