---
name: inquiry
pack: test
description: Notify relevant users of an Inquiry action
enabled: true

trigger:
  type: core.st2.generic.inquiry

# action:
#   ref: core.echo
#   parameters:
#     message: |
#       Trigger:
#       {{ trigger | to_yaml_string }}

action:
  ref: slack.chat.postMessage
  parameters:
    channel: "#{{ trigger.route }}"
    text: |
      Inquiry `{{ trigger.id }}` waiting ...
    thread_ts: "{{ st2kv.system.slack_thread_ts }}"
