---
name: kvp-create
pack: test
description: KV pair create rule
enabled: false

trigger:
  type: core.st2.key_value_pair.create

criteria:
  trigger.object.name:
    type: equals
    pattern: foo

action:
  ref: core.echo
  parameters:
    message: |
      {{ trigger | to_yaml_string }}
      {{ trigger.object.name }}
