---
name: rule1
pack: test
description: Rule on test.event1
enabled: true

trigger:
    type: test.event1

criteria:
    trigger.things:
        type: search
        condition: any
        pattern:
            item.number:
                type: equals
                pattern: 2

action:
    ref: test.greet
    parameters:
        greeting: Yo
