---
name: yum
pack: test
description: Rule on test.event1
enabled: false

trigger:
    type: test.yum

criteria:
    trigger.host1:
        type: greaterthan
        pattern: 0

action:
    ref: core.echo
    parameters:
        message: "host1 needs yum update for {{ trigger.host1 }} packages"
